#pragma config(Sensor, S2,     giro,           sensorEV3_Gyro)
#pragma config(Sensor, S3,     sencolor,       sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S1,     ultrasonic,     sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          ruedad2,       tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          ruedatr1,      tmotorEV3_Large, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC,          ruedatr2,      tmotorEV3_Large, PIDControl, reversed, encoder)
#pragma config(Motor,  motorD,          ruedad,        tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int vida = 1;
int contvida = 1;



task main(){
	while (true){
		eraseDisplay();
		displayStringAt(70,60,"%d vida",vida);
		motor[ruedatr1] = 25;
		motor[ruedatr2] = 25;
		motor[ruedad] = 25;
		motor[ruedad2] = 25;
		while(SensorValue[ultrasonic] < (50)){
			setMotorSpeed(motorB, 100);
			setMotorSpeed(motorC, 100);
			setMotorSpeed(motorD, 100);
			setMotorSpeed(motorA, 100);
			setSoundVolume(100);
			playSound(soundBeepBeep);
		}
		if (SensorValue[sencolor] == 1)  {
			motor[ruedatr1] = -25;
			motor[ruedatr2] = -25;
			motor[ruedad] = -25;
			motor[ruedad2] = -25;
			wait1Msec(1000);
			motor[ruedatr1] = -25;
			motor[ruedatr2] = 25;
			motor[ruedad] = -25;
			motor[ruedad2] = 25;
			wait1Msec(1000);
			continue;

		}

	}
}
